package constants

const (
	LogUserRegisterSuccess    = "user register success: username=%s"
	LogUserRegisterFailed     = "user register failed: username=%s"
	LogUserLoginSuccess       = "user login success: username=%s"
	LogUserLoginFailed        = "user login failed: username=%s"
	LogUserProfileUpdated     = "user profile updated: user_id=%d"
	LogNoteCreateSuccess      = "tasting note created: coffee_name=%s"
	LogNoteCreateFailed       = "tasting note create failed: coffee_name=%s"
	LogNoteUpdateSuccess      = "tasting note updated: id=%d"
	LogNoteDeleteSuccess      = "tasting note deleted: id=%d"
	LogNoteListSuccess        = "tasting note list success: roast=%s page=%d"
	LogNoteLikeSuccess        = "tasting note liked: id=%d"
	LogNoteLikeFailed         = "tasting note like failed: id=%d"
	LogCommentCreateSuccess   = "comment created: note_id=%d"
	LogCommentDeleteSuccess   = "comment deleted: id=%d"
	LogRecipeCreateSuccess    = "brew recipe created: name=%s"
	LogRecipeCreateFailed     = "brew recipe create failed: name=%s"
	LogRecipeListSuccess      = "brew recipe list success: device=%s"
	LogBeanCreateSuccess      = "coffee bean created: name=%s"
	LogBeanCreateFailed       = "coffee bean create failed: name=%s"
	LogBeanUpdateSuccess      = "coffee bean updated: id=%d"
	LogBeanDeleteSuccess      = "coffee bean deleted: id=%d"
	LogBeanListSuccess        = "coffee bean list success: process=%s"
	LogFollowSuccess          = "user follow success: follower=%d following=%d"
	LogUnfollowSuccess        = "user unfollow success: follower=%d following=%d"
	LogProfileStats           = "profile stats computed: user_id=%d"
	LogUploadSuccess          = "file upload success: filename=%s"
	LogUploadFailed           = "file upload failed: filename=%s"
	LogRateLimited            = "request rate limited: path=%s ip=%s"
	LogRequestHandled         = "request handled: request_id=%s method=%s path=%s status=%d latency_ms=%d"
)
